### ISSUE TITLE
Two silent issues when loading package - SQL heatmap and "Geocoding Providers" duplicate node name

### ISSUE THREAD

**Issue by samuelscandrett** [archesproject/arches-example-pkg#6]
Two silent issues occur when loading the master branch (and dev/7.4.x) package. 
Neither of these errors prevent the package from completing loading, but they have been mentioned in the forum - https://community.archesproject.org/t/failure-in-production/2117/3.

The first is related to the search result heatmap in the preliminary sql, which shows the error
```
loading preliminary sql
null value in column "searchonly" violates not-null constraint
DETAIL:  Failing row contains (1b7aa554-5e0e-11ee-b2ec-f3c16dd8751c, Search Results, [{"id": "search-results-heat", "type": "heatmap", "paint": {"hea..., t, ion-search, t, t, null, null, null, null, null, null, null).

Failed to load sql files
```

The second is related to a duplicate node name in the Settings Map.json. 
```
/mnt/c/testing/v7test/v7test/_pkg_230928_094748/arches-example-pkg-master/graphs/branches/Settings Map.json
2023-09-28 09:50:44,671 arches.app.utils.data_management.resource_graphs.importer ERROR    'Duplicate node name: "Geocoding Providers". All node names in a card must be unique.'
Traceback (most recent call last):
  File "/mnt/c/testing/v7test/arches/arches/app/utils/data_management/resource_graphs/importer.py", line 128, in import_graph
    graph.save()
  File "/mnt/c/testing/v7test/arches/arches/app/models/graph.py", line 475, in save
    self.validate()
  File "/mnt/c/testing/v7test/arches/arches/app/models/graph.py", line 1667, in validate
    self._validate_node_name(node)
  File "/mnt/c/testing/v7test/arches/arches/app/models/graph.py", line 1588, in _validate_node_name
    raise GraphValidationError(message)
arches.app.models.graph.GraphValidationError: 'Duplicate node name: "Geocoding Providers". All node names in a card must be unique.'
```
Despite the error stating the name is a duplicate, "Geocoding Providers" only appears to show up once in the Settings Map.json which is odd.

**Comment by chiatt** [comment]
Hmm.. I wonder if that sql has been updated to work with 7.4
